### ISSUE TITLE
ALL CAMERAS ARE NOT RESPONDING!

### ISSUE THREAD

**Issue by Seme100** [goruck/alexa-ip-cam#2]
Hello, 
i used your Code as a skill for a few weeks (3 cams). 
Since March, 22 Amazon has changed something.
now if I call "show door"  Alexa says "Camera is not responding". In German "Die Kamera reagiert gerade nicht"
On 2 Forums i could find the same Problems from Users have other Skills eg "Monocle".
Cams that are compatible with Alexa, don't have the Problem...
Read this
https://forums.developer.amazon.com/questions/140767/help-all-cameras-are-not-responding-was-working-fi.html

**Comment by goruck** [comment]
Hi,
I do not see this problem on my setup. The skill is working correctly for all cameras. 

Do you see any errors in your skill's Cloudwatch logs?

Also, you could try deleting the cameras from the Alexa app and then asking Alexa to discover devices again. In any event this should tell you if Alexa is even seeing the cameras as smart home devices.

Hope this helps.

Lindo

**Comment by Seme100** [comment]
Hi,
i didn't change your script (except for URL and settings in cameras.json), everyhting worked correctly. Until March 22. 
As you can read, other skills like Monocle (showing IP-Cam on Echo Show or spot) have the same problem.
I think, Amazon changed something (maybe the handling), for example are there additional Parameters so that perhaps the file index.js must be changed?
I deleted and discovered all 3 devices - that's not the problem. This part is still working.
I'm not familiar with Cloudwatch-logs, but i'll try to understand and if i find something, i'll write here.

**Comment by goruck** [comment]
Hi,
The skill's lambda function will log information to CloudWatch which is another AWS service. You can find CloudWatch in the AWS console. Here you should see an entry for the lambda function that was triggered by the skill once you invoked it under a path like CloudWatch > Log Groups  > Streams > ShowCameras. 
Thanks.
Lindo

**Comment by savageautomate** [comment]
@Seme100,

FYI, **Monocle** (https://monoclecam.com/) is working again.  

Around March 22, Amazon started enforcing their documented requirements.  You may now only use port 443 to host your cameras.  You must have a TLS encrypted endpoint.  You must have a valid SSL certificate.  You must be using a fully qualified DNS hostname rather than an IP address.

Thanks, Robert

**Comment by goruck** [comment]
Yes, correct. the alexa-ip-cam does adhere to these requirements.
