### ISSUE TITLE
domain and TLS certs problem

### ISSUE THREAD

**Issue by chaoshendasixiong** [goruck/alexa-ip-cam#8]
Hi,
I noticed 2 prerequisites.
It means that each camera needs to have its own separate domain name and certificate?
or,
One domain name is enough and use subdomain identify different cameras?
Live555's proxy address format is rtsp://domain:443:/proxyStream-1 , .../proxyStream-2
I see that "officecamerapi.dev-cloud.co.uk:443/h264, rtsp://hallcamerapi.dev-cloud.co.uk:443/h264"
Are u have 2 live555 process to proxy 2 camera rtsp feed?

**Comment by goruck** [comment]
@chaoshendasixiong - only one domain is required. A single live555 proxy aggregates all camera streams into one front end stream and will be at rtsp://HOST_IP:554/proxyStream-n, where n is the order of the input streams given to the proxy. See [proxy-start.sh
](https://github.com/goruck/alexa-ip-cam/blob/master/proxy-start.sh) for how this is done at start up. 

Hope this addresses your question, if not let me know.

**Comment by chaoshendasixiong** [comment]
I tried it according to your tutorial. I used nginx's tcp instead of stunnel.
But I don't understand that echo show needs DNS resolution to lan's ip address. Have you ever thought about using redirect which in RTSP protocol to avoid using live555, as if echo show uses the redirect address to play the rtsp stream from the camera, like VLC. 
I don't want to put live555ProxyServer at home, it would be more easy if it is hosted in the cloud. I only need to ensure that the rtsp address that with the camera is passed to the echo show via redirect.
The only problem is whether echo show is still forced to encrypt feed with tls1.2 after redirect.

**Comment by goruck** [comment]
"But I don't understand that echo show needs DNS resolution"

The Alexa.CameraStreamController Interface requires TCP socket encryption on port 443 using TLS 1.2. So you need a valid cert (self signed certs are not allowed) and the project uses DNS to validate domain ownership.

"I don't want to put live555ProxyServer at home, it would be more easy if it is hosted in the cloud. I only need to ensure that the rtsp address that with the camera is passed to the echo show via redirect."

I guess as long as you could encrypt the feed properly as explained above I don't see why this would not work.
